### ISSUE TITLE
Split long commands syntax not supported

### ISSUE THREAD

**Issue by ookami125** [mdubourg001/glci#13]
When running a task formatted as so:
```yaml
pre:
  stage: pre-prepare
  script: |
    mkdir -p test1
    touch test1/test.txt

  artifacts:
    paths:
      - test1
```
it causes script to be read as a string and not an array.
I fixed it with adding this to the top of the execCommands function in index.
```js
if(typeof commands === 'string' || commands instanceof String)
    commands = [commands];
```
I don't really have the time to submit a pull request right now or even manage it so I figured this would be a better option.
