### ISSUE TITLE
OCI runtime exec failed

### ISSUE THREAD

**Issue by lazzarello** [mdubourg001/glci#14]
This same branch / commit ID builds successfully on my Gitlab server but when run locally with glci I get the following error.

```
$ glci --only-jobs=build
-----------------------------------------------
Running job "build" for stage "build"
-----------------------------------------------

ℹ - Using existing image "gcr.io/kaniko-project/executor:debug"
mkdir -p /root/.docker
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "process_linux.go:101: executing setns process caused \"exit status 1\"": unknown
✘  - build
```
The build stage in my .gitlab-ci.yml looks like this

```
build:
  stage: build
  image: gcr.io/kaniko-project/executor:debug
  before_script:
    - mkdir -p /root/.docker
    - echo $DOCKER_AUTH_CONFIG > /root/.docker/config.json
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $RUN_TAG --destination $BRANCH_TAG --destination $COMMIT_TAG
  tags:
    - kubernetes
  variables:
    GIT_SUBMODULE_STRATEGY: normal
```
