### ISSUE TITLE
Extending hidden jobs does not work

### ISSUE THREAD

**Issue by justfortherec** [mdubourg001/glci#23]
In my production CI configuration (which works in Gitlab), I ran into #19. The proposed solution there is to add a missing `image.name`. Images are defined in my CI definition, so I am trying to figure out what causes `glci` to not find this information. We use `extends` with [hidden jobs](https://docs.gitlab.com/ee/ci/yaml/#hide-jobs) from `include`d YAML files.

When trying to distill a minimum example to reproduce the issue, I ran into the following problems.

### First attempt

In my first attempt, I defined one template and one job directly in `.gitlab-ci.yml`:

```yaml
.example-template:
    image:
        name: alpine

example-job:
    extends:
        - .example-template
    script:
        echo "Hello World"
```

This works in Gitlab but fails when running `glci` (but not with the error from #19 which I tried to reproduce):

```
> glci
(node:58265) UnhandledPromiseRejectionWarning: Error: could not find repository from '.'
(node:58265) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:58265) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I don't know what's going on here, so I switched to another approach.

### Second attempt

Next, I tried splitting the files and including them in `.gitlab-ci.yml` (like I do in my production CI config):

#### `.gitlab-ci.yml`
```yaml
include:
    - local: .gitlab/ci/template.gitlab-ci.yml
    - local: .gitlab/ci/example.gitlab-ci.yml
```
#### `.gitlab/ci/template.gitlab-ci.yml`

```yaml
.example-template:
    image:
        name: alpine
```

#### `.gitlab/ci/example.gitlab-ci.yml`

```yaml
example-job:
    extends:
        - .example-template
    script:
        echo "Hello World"
```

This also works in Gitlab but fails for yet another reason with `glci`:

```
> glci
----------------------------------------------------------
Running job ".example-template" for stage "test"
----------------------------------------------------------

ℹ - Pulling image "alpine"...
TypeError: commands is not iterable
✘  - .example-template
```
Here, it seems as if `glci` tries to run the [hidden job](https://docs.gitlab.com/ee/ci/yaml/#hide-jobs) instead of just using it as a template.

At this point my list of one issue has grown to three and I am stopping my attempts to reproduce the issue for the time being. I am happy to assist in further debugging though. `glci` seems like it has great potential for faster iterations on Gitlab CI configuration after all.
