### ISSUE TITLE
`extends:` is not treated as array

### ISSUE THREAD

**Issue by justfortherec** [mdubourg001/glci#27]
Thank you for quickly adding the requested `extends` functionality. Unfortunately, it only works for a single template while `extends:` is an array.

To reproduce, try this `.gitlab-ci.yml` file:
```yaml
.first-example-template:
    image:
        name: alpine

.second-example-template:
    only:
        refs:
            - master

example-job:
    extends:
        - .first-example-template
        - .second-example-template
    script:
        echo "Hello World"
```

It seems as if `glci` joins the names of the extended jobs instead of iterating over them:
```
> glci
Can't extend job '.first-example-template,.second-example-template': job doesn't exist.
```
