### ISSUE TITLE
Extends with included, local yml files doesn't find job

### ISSUE THREAD

**Issue by renestalder** [mdubourg001/glci#33]
When trying to use `extends` with a job defined in locally included yml file, glci 0.4.1 tells me, `Can't extend job '.docker_build': job doesn't exist.`.

Simplified example:

docker.yml

```yml
.docker_build:
  image: docker:stable
  scripts:
    .
```

.gitlab-ci.yml
```yml
include:
  - local: '/gitlab-ci-templates/docker.yml'

my job:
  extends: .docker_build
  variables:
    ...
```

That example works on GitLab.com.

Is this a limitation of glci or a bug?
