### ISSUE TITLE
docker pull fails

### ISSUE THREAD

**Issue by SuperSandro2000** [mdubourg001/glci#34]
My user does not have the docker group and I normally run docker with sudo. Might this be the cause of the crash?

```
---------------------------------------------------------------
Running job "build-image" for stage "build-1"
---------------------------------------------------------------

TypeError: Cannot read property 'indexOf' of undefined
    at Object.module.exports.parseRepositoryTag (/home/user/.config/yarn/global/node_modules/dockerode/lib/util.js:42:25)
    at Docker.pull (/home/user/.config/yarn/global/node_modules/dockerode/lib/docker.js:1411:23)
    at /home/user/.config/yarn/global/node_modules/glci/dist/cli.min.js:637:55
    at new Promise (<anonymous>)
    at main$1 (/home/user/.config/yarn/global/node_modules/glci/dist/cli.min.js:637:15)
✘  - build-image
```

**Comment by mdubourg001** [comment]
Could you provide a copy of your `.gitlab-ci.yml` file please ?

**Comment by SuperSandro2000** [comment]
```yaml
variables:
  IMAGE: docker-registry.company.com/group/repo/ci

build-image:
  stage: build
  tags:
    - docker-host
  only:
    refs:
      - master
    changes:
      - continuous_integration/Dockerfile
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t "$IMAGE" -f continuous_integration/Dockerfile .
    - docker push "$IMAGE"
```
